spring:
  application:
    name: eureka

server:
  port: 8761
  servlet:
    context-path: /registry

eureka:
  server:
    port: 8761
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka/
logging:
  file.max-history: 5
  level:
    root: INFO
  file:
    name: ${logging.dir}/${spring.application.name}.log
#logging:
#  level:
#    com:
#      netflix:
#        eureka: true
#        discovery: true